version: "3.2"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - wikiquiz-network

  wikiquiz-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env
    links:
      - mongo
    networks:
      - wikiquiz-network

networks:
  wikiquiz-network:
